config/routes.rb
Rails.application.routes.draw do

  resources :song_requests

  resources :pictures

  resources :tables do
    member do
	   get :empty
	end
  end

  root               		'static_pages#home'
  get 		'home'    	=> 	'static_pages#home'
  get 		'about'   	=>  'static_pages#about'
  get		'wedding' 	=>  'static_pages#wedding'
  get		'venue_cost' 	=>  'static_pages#venue_cost'
  get		'our_story' =>  'static_pages#our_story'
  get		'contact_us' =>  'static_pages#contact_us'
  get		'signup'  	=>	'users#new'
  get    	'login'   	=> 	'sessions#new'
  post   	'login'   	=> 	'sessions#create'
  delete 	'logout'  	=> 	'sessions#destroy'
  get       'flip_theme'    =>      'tables#flip_theme'
  post      'twilio/voice'   =>  'twilio#voice'
  post      'twilio/notify'  =>  'twilio#notify'
  get       'coming_guests' => 'users#index_coming'

  resources :users do
  	member do
  		get :activate
  		get :deactivate
  		get :invite
  		get :uninvite
  		get :iscoming
  		get :isnotcoming
  		get :set_is_not_adult
  		get :set_is_adult
        get ':action/:table_id'
        get :untable
  	end
    resources :tables do
        member do
		   get :add_user
		   get :remove_user
        end
		  
     end
  end
  
  resources :guess_who_questions do
  	member do
  		get :save_user_answer
  	end
  end
  
  resources :families do
    member do
        get :untable
  	end
  
	resources :tables do
        member do
		   get :add_family
           get :remove_family
        end
	end
  end
  
  resources :messages do
  	member do
  		get :mark_as_read
  		get :mark_as_unread
  	end
  end
  
  resources :account_activations, only: [:edit]

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
 
  before_action :logged_in_user, only: [:wedding]
  
  def home
    if logged_in?
      current_user.increment_login
    end 
  end

  def about
  end
  
  def contact_us
  	contact_us_path
  end
  
  def wedding
    if params[:commit]
  	  current_user.update_attribute(:is_coming, get_rsvp(params[:commit]))
  	end
    wedding_path
  end 
  
  private

    def user_params
      params.require(:user).permit(:first_name, 
      								:last_name, 
      								:email,
      								:address, 
      								:admin, 
      								:invited, 
      								:is_coming,
      								:password,
      								:password_confirmation)
    end
    
    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
  def can_rsvp?
  	 get_days_left <= 90
  end
  
  def get_rsvp_date
  	 wedding_date = Date.new(2015,7,30)
  	 rsvp_date = (wedding_date - 90)
  end
  
  def get_rsvp(option)
     if get_yes_options.include?(option)
        flash[:success] = "We are delighted to have you with us!"
        true
     elsif get_no_options.include?(option)
        flash[:success] = "We will definitely miss you!"
        false
     end
  end
  
  def get_yes_options
     rsvp_options = ["I'll Be There In Person :)", "I have my outfit ready :)"]
  end
  
  def get_no_options
     rsvp_options = ["I'll Be There In Spirit :(", "I broke my ankle and will miss it :("]
  end
  
  def get_options
     rsvp_options = get_yes_options
     rsvp_options.concat(get_no_options)
  end

end

app/views/static_pages/contact_us.html.erb
<% provide(:title, "Contact Us") %>

<h1>Contact Us</h1>

<section class="wedding_info" >
<h3>By Email</h3>
<p>
samanthalouis.12@gmail.com<br>
titbabthomas@gmail.com<br>
</p>

<h3>By Phone</h3>
<p>
404-545-2623<br>
404-219-2104<br>
</p>

</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Sam & Seb's Website</h1>

  <h2>  
  </h2>
  <% if logged_in? %>
  <%= link_to "Wedding Info", wedding_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Guess Who! (#{current_user.get_answered_questions_count}/#{guess_who_questions_count} answered)", guess_who_questions_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Request Songs", new_song_request_path, class: "btn btn-lg btn-primary" %>
  <% if current_user.admin? %>
  <%= link_to "Our Story", our_story_path, class: "btn btn-lg btn-primary" %>
  <% end %>
  <p>
  </p>
  
  <p>
  Hi <%= current_user.first_name %>,<br>
  <br>
  Once again thank you for being a part of our lives.<br>
  We are really excited about our upcoming big day and having you with us.<br>
  As we are getting closer to the date, we will be updating the site.<br>
  Hence please don't forget to come back to participate in all the fun we have in store.<br>
  <br>
  Love,<br>
  Sam & Seb
  </p>
  
  <h2 style="color:green">Breaking News!!!</h2>
  <p>
  <ul>
     <li>The more you stalk our website, the better your chances to win. So make sure you come back daily ;). You have <%= current_user.logins %> login points so far!!!</li>
	 <li>You also get more points for requesting songs!!! You have <%= current_user.song_requests.size %> requets points so far!!!</li>
	 <li style="color:red">You want more points? For every 7 songs you request, you get 1 extra request per day! You have <%= current_user.request_extra %> extra requests per day!</li>
  </ul>
  </p>
  <% else %>
  	<p>
  	Please log in or <%= link_to "contact us", new_message_path %> to see more.
    </p>
<% end %>
</div>
<div class="center jumbotron">  
	<%= image_tag(random_pic, :height => "auto", :width => "75%", alt: random_pic) %>
</div>

app/views/static_pages/our_story.html.erb
<% provide(:title, "Our Story") %>

<div class="center jumbotron">
  <h1>Our Story</h1>
</div>

<div id="left_section">
<%= image_tag(random_pic, :height => "100%", :width => "100%", alt: random_pic) %>
</div>


<div id="right_section"> 
  <p>
  Once upon a time...<br>
  <br>
  There was a little boy named Sebastien. He met a nice little girl name Samantha.
  They grew up in a small city in Haiti named Port-au-Prince. They barely talked to 
  eachother the rare times they would see eachother at birthday parties.
  As they grew older they got closer to eachother and became great friends.
  With time they got so close to eachother that they knew about eachother's secrets.
  They had no clue that they were about to be more then best friends.
  </p>
  <p>
  One day, as Sebastien was going through some young man story and needed advice from his best friend, 
  a little bird told Sebastien: "Why are you not with Samantha?" That little bird told Samantha the same
  thing: "Why are you not with Sebastien?" And that was the beginning of the more than just best friend part of our lives.
  </p>
  <p>
  To be continued...
  </p>
</div>

app/views/static_pages/venue_cost.erb
<% provide(:title, "Wedding Info") %>
<div class="center jumbotron">
	<h1>Final Guests Count</h1>
	<h3>Guests: <%= adult_count %> @ $<%= format(adult_cost) %> => $<%= format(adult_total_cost) %></h3>
	<h3>Children: <%= child_count %> @ $<%= format(child_vendor_cost) %> => $<%= format(child_total_cost) %></h3>
	<h3>Vendors: <%= vendor_count %> @ $<%= format(child_vendor_cost) %> => $<%= format(vendor_total_cost) %></h3>
	<h3>Subtotal: $<%= format(subtotal) %></h3>
	<h3>Tax @ 8.625% => $<%= format(tax_amount) %></h3>
	<h3>TOTAL => $<%= format(after_tax_total) %></h3>
	<h3>Deposit => $<%= format(deposit) %></h3>
	<h3>Current Check => $<%= format(current_check) %></h3>
	<h3>Due => $<%= format(balance) %></h3>
</div>

app/views/static_pages/wedding.html.erb
<% provide(:title, "Wedding Info") %>
<div class="center jumbotron">
  <h1><%= get_days_left %> days until We Become One!!!</h1>
  
<div class="rsvp">
<% if logged_in_admin? || can_rsvp? %>
	<h2>RSVP:</h2>
	<%= form_tag(wedding_path, method: "get") do %>
	 <% (0..get_options.length-1).each do |i| %>
		<%= submit_tag get_options.at(i), class: "btn btn-lg btn-primary" %>
	  <% end %>
	<% end %>
<% else %>
	<h2>Please come back on or after <%= get_rsvp_date %> to rsvp. Thank you!</h2>
<% end %>
</div>

</div>

<section class="wedding_info" >
<h3>Date</h3>
<p>
Thursday, the thirtieth of July<br>
two thousand and fifteen<br>
at five o'clock in the afternoon
</p>

<h3>Ceremony</h3>
<p>
St. Thomas the Apostle Church<br>
24 Westminster Road<br>
West Hempstead, NY 11552
</p>

<h3>Reception</h3>
<p>
Westbury Manor<br>
1100 Jericho Turnpike<br>
Westbury, NY 11590
</p>

<h3>Registries</h3>

<ul>
<li><a href="https://www.jcpenney.com/dotcom/jsp/giftregistry/gifterGiftList/gifterGiftList.jsp?filterBy=viewAll&regId=80060645&sort=category&view=list&viewType=PUBLIC"> JC Penny </a></li>
<li><a href="http://www1.macys.com/registry/wedding/guest/?registryId=6297389"> Macy's </a></li>
<li><a href="http://carnival.honeymoonwishes.com/Honeymoon-Registry-261057-Carnival-Eastern-Caribbean-Emmanuel-Thomas-Samantha-Louis.html"> Carnival Cruise</a></li>
</ul>

</section>