config/routes.rb
Rails.application.routes.draw do

  resources :song_requests

  resources :pictures

  resources :tables do
    member do
	   get :empty
	end
  end

  root               		'static_pages#home'
  get 		'home'    	=> 	'static_pages#home'
  get 		'about'   	=>  'static_pages#about'
  get		'wedding' 	=>  'static_pages#wedding'
  get		'venue_cost' 	=>  'static_pages#venue_cost'
  get		'our_story' =>  'static_pages#our_story'
  get		'contact_us' =>  'static_pages#contact_us'
  get		'signup'  	=>	'users#new'
  get    	'login'   	=> 	'sessions#new'
  post   	'login'   	=> 	'sessions#create'
  delete 	'logout'  	=> 	'sessions#destroy'
  get       'flip_theme'    =>      'tables#flip_theme'
  post      'twilio/voice'   =>  'twilio#voice'
  post      'twilio/notify'  =>  'twilio#notify'
  get       'coming_guests' => 'users#index_coming'

  resources :users do
  	member do
  		get :activate
  		get :deactivate
  		get :invite
  		get :uninvite
  		get :iscoming
  		get :isnotcoming
  		get :set_is_not_adult
  		get :set_is_adult
        get ':action/:table_id'
        get :untable
  	end
    resources :tables do
        member do
		   get :add_user
		   get :remove_user
        end
		  
     end
  end
  
  resources :guess_who_questions do
  	member do
  		get :save_user_answer
  	end
  end
  
  resources :families do
    member do
        get :untable
  	end
  
	resources :tables do
        member do
		   get :add_family
           get :remove_family
        end
	end
  end
  
  resources :messages do
  	member do
  		get :mark_as_read
  		get :mark_as_unread
  	end
  end
  
  resources :account_activations, only: [:edit]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :table
  belongs_to :family
  has_many :song_requests

  attr_accessor :remember_token
  attr_accessor :activation_token
  attr_accessor :view_as_guest
  
  def flip_theme
    if self.theme == 1
       update_attribute(:theme,0)
    else
       update_attribute(:theme,1)
    end
  end
  
  def get_theme
    self.theme == 1 ? "destination" : "beach"
  end

  before_save do 
  	self.email = email.downcase if !email.nil?
  	self.email = nil if (!email.nil? && email.empty?)
    self.address = nil if (!address.nil? && address.empty?)
  	self.username = (last_name.gsub(/[^0-9a-z]/i, '')+"."+first_name.gsub(/[^0-9a-z]/i, '')).downcase
	self.table_id = nil if !is_coming
  end
  
  before_create :create_activation_digest
  
  after_create do 
  	self.username = (last_name.gsub(/[^0-9a-z]/i, '')+"."+first_name.gsub(/[^0-9a-z]/i, '')).downcase
  end
  
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    allow_blank: true

  validates :address, length: { maximum: 255 }, allow_blank: true
                   
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def has_default_pass?
  	return self.authenticate('password') == self
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  # Deactivates an account.
  def deactivate
    update_attribute(:activated, false)
    update_attribute(:activated_at, Time.zone.now)
    self.password = "password"
    self.password_confirmation = "password"
    self.save
    
  end

  def increment_login
    if !self.last_login? || self.last_login < Date.today
       increment!(:logins)
       update_attribute(:last_login, Date.today)
    end
  end

  def get_answered_questions_count
    GuessWhoUserAnswer.where(:user_id => self.id).count
  end

  def get_guess_who_right_answers_count
    GuessWhoUserAnswer.where(:user_id => self.id).joins("JOIN guess_who_questions ON guess_who_questions.id = guess_who_user_answers.guess_who_question_id AND guess_who_questions.answer = guess_who_user_answers.answer").count
  end
  
  def get_total_points
    get_answered_questions_count*0.25 + get_guess_who_right_answers_count*0.25 + song_requests.size*0.25 + logins*0.25
  end
  
  def get_request_count
    song_requests.size
  end
  
  def set_is_adult
    update_attribute(:is_adult, true)
  end
  
  def set_is_not_adult
    update_attribute(:is_adult, false)
  end

  def untable 
    update_attribute(:table_id, nil)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  def view_as_guest?
	  if self.view_as_guest.nil?
		self.view_as_guest = true
	  end
	  return self.view_as_guest
  end
  
  def set_view_as_guest(option)
  	self.view_as_guest = option
  end
  
  def get_table
    if self.table
       self.table.number
    end
  end  

  def request_allowed
	   (self.song_requests.size.to_i / 7) + 1  
  end
  
  def request_extra
	   self.song_requests.size.to_i / 7  
  end
  
  def request_today
	   self.song_requests.where("DATE(created_at) = DATE(?)", Time.now).size  
  end
	
  private
	
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase unless email.nil?
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'will_paginate/array'

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,	 only: [:index, :destroy, :show]
  
  skip_before_action :log_user_out, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    if params[:commit]
    	@user = User.create(first_name: params[:first_name], 
							last_name: params[:last_name],
							password: "password", 
							password_confirmation: "password")
							
    	if @user.save
  			flash[:success] = @user.first_name+" was Added"
  		else
  			flash[:danger] = "There was an error"
  		end
  		
  		redirect_to users_path
    else
    	@user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      if !@user.email.nil?
         @user.send_activation_email
      end
       
      if logged_in_admin?
        flash[:success] = "Account Created"
    	redirect_to users_path
      else 
        flash[:info] = "Please check your email to activate your account."
      	redirect_to root_url
      end

    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  # Activate a user in the database
  def activate
    @user = User.find(params[:id])
    @user.activate
    redirect_to :back
  end
  
  # Activate a user in the database
  def deactivate
    @user = User.find(params[:id])
    @user.deactivate
    redirect_to :back
  end
  
  # Activate a user in the database
  def set_is_adult
    @user = User.find(params[:id])
    @user.set_is_adult
    redirect_to :back
  end

  def untable
    @user = User.find(params[:id])
    @user.untable
    redirect_to :back
  end
  
  # Activate a user in the database
  def set_is_not_adult
    @user = User.find(params[:id])
    @user.set_is_not_adult
    redirect_to :back
  end
  
  def invite
  	@user = User.find(params[:id])
    @user.update_attribute(:invited, true)
    redirect_to :back
  end
  
  def uninvite
  	@user = User.find(params[:id])
    @user.update_attribute(:invited, false)
    redirect_to :back
  end
  
  def iscoming
  	@user = User.find(params[:id])
    @user.update_attribute(:is_coming, true)
    flash[:success] = params
    redirect_to :back
  end
  
  def isnotcoming
  	@user = User.find(params[:id])
    @user.update_attribute(:is_coming, false)
    redirect_to :back
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to :back
  end
  
  def update
  	flash[:danger] = "Please change your password."
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if logged_in_admin?
      	 flash[:success] = "#{@user.first_name}'s profile updated"
      	 redirect_to users_path
      else
    	 if @user.has_default_pass?
    	 	flash.now[:danger] = 'Please change your password!'
    	 	render 'edit'
    	 else
    	 	@user.activate
            redirect_to @user
         end
      end 
    else
      render 'edit'
    end
  end
  
  def index
       @users = User.joins(:family)
       		    .where(params[:address_param])
                    .where(params[:email_param])
                    .where(params[:admin_param])
                    .where(params[:invited_param])
                    .where(params[:activated_param])
                    .where(params[:is_coming_param])
                    .where(params[:is_adult_param])
                    .where("LOWER(first_name) LIKE '%#{params[:name_filter_param]}%' OR LOWER(last_name) LIKE '%#{params[:name_filter_param]}%'")
                    .order(:last_name)
					
		 unless params[:sort_by_param].blank?
		   if params[:sort_by_param] == 'points'
              @users = @users.sort_by(&:get_total_points).reverse			  
           elsif params[:sort_by_param] == 'logins'
              @users = @users.sort_by(&:logins).reverse			  
           elsif params[:sort_by_param] == 'requests'
              @users = @users.sort_by(&:get_request_count).reverse			  
           elsif params[:sort_by_param] == 'answers'
              @users = @users.sort_by(&:get_answered_questions_count).reverse
           end		   
		 end
		 
		 unless params[:seated_param].blank?
		   if params[:seated_param] == 'true'
              @users = @users.joins(:table)			  
           elsif params[:seated_param] == 'false'
			  @seated_users = User.joins(:table)
			  @users = @users - @seated_users
           end		   
		 end
		 
		 unless params[:first_name_in_filter_param].blank?
		   first_names = params[:first_name_in_filter_param].gsub(/\s/i, '').split(",")
		   flash.now[:danger] = first_names
		   @users = @users.where(first_name: first_names)
		 end
	    
       @users = @users.paginate(page: params[:page], per_page: 25)
       @available_tables = Table.joins("LEFT OUTER JOIN users on users.table_id = tables.id").group(:number).having("count(*)<max(capacity)")
  end
  
  def index_coming
       @count = 0
       @users = User.where("is_coming = 1").order(:last_name).order(:first_name)
	   render 'users/index_coming'
  end
  
  private

    def user_params
     # params.require(:user).permit(:first_name, 
     # 								:last_name, 
     # 								:email,
     # 								:address, 
     # 								:admin, 
     # 								:invited, 
     # 								:is_coming,
     # 								:password,
     # 								:password_confirmation)
     params.require(:user).permit!
    end
    
    # Before filters

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.username)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
  
  def full_name(user)
     user.last_name+", "+user.first_name
  end
  
  def username(user)
     (user.last_name.gsub(/[^0-9a-z]/i, '')+"."+user.first_name.gsub(/[^0-9a-z]/i, '')).downcase
  end
  
  def is_admin(user)
     user.admin
  end

end

app/views/users/_filters.html.erb
<div class="filters" >
<%= form_tag(users_path, method: "get") do %>
<table>
<tr>
    <th><%= label_tag(:name_filter_param, "Name Contains:") %></th>
	<th><%= label_tag(:first_name_in_filter_param, "First Name In: (ex: sebastien,samantha)") %></th>
    <th><%= label_tag(:address_param, "Address:") %></th>
    <th><%= label_tag(:email_param, "Email:") %></th>
    <th><%= label_tag(:admin_param, "Admin:") %></th>
    <th><%= label_tag(:invited_param, "Logged In:") %></th>
</tr>
<tr>
	<td><%= text_field_tag :name_filter_param %></td>
	<td><%= text_field_tag :first_name_in_filter_param %></td>
	<td><%= select_tag(:address_param, options_for_select([['All', ''], ['Unknown', 'address is null'], ['Known', 'address is not null']]) )%></td>
	<td><%= select_tag(:email_param, options_for_select([['All', ''], ['Unknown', 'email is null'], ['Known', 'email is not null']]) )%></td>
	<td><%= select_tag(:admin_param, options_for_select([['All', ''], ['Yes', 'admin = 1'], ['No', 'admin = 0']]) )%></td>
	<td><%= select_tag(:invited_param, options_for_select([['All', ''], ['Yes', 'logins > 0'], ['No', 'logins = 0']]) )%></td>
</tr>
<tr>
    <th><%= label_tag(:is_coming_param, "Is Coming:") %></th>
    <th><%= label_tag(:is_adult_param, "Is Adult:") %></th>
    <th><%= label_tag(:activated_param, "Is Activated:") %></th>
	<th><%= label_tag(:seated_param, "Is Seated:") %></th>
	<th><%= label_tag(:sort_by_param, "Sorted By:") %></th>
</tr>
<tr>
	<td><%= select_tag(:is_coming_param, options_for_select([['All', ''], ['Yes', 'is_coming = 1'], ['No', 'is_coming = 0']]) )%></td>
	<td><%= select_tag(:is_adult_param, options_for_select([['All', ''], ['Yes', 'is_adult = 1'], ['No', 'is_adult = 0']]) )%></td>
	<td><%= select_tag(:activated_param, options_for_select([['All', ''], ['Yes', 'activated = 1'], ['No', 'activated = 0']]) )%></td>
	<td><%= select_tag(:seated_param, options_for_select([['All', nil], ['Yes', true], ['No', false]]) )%></td>
	<td><%= select_tag(:sort_by_param, options_for_select([['', nil], ['Points', 'points'], ['Logins', 'logins'], ['Requests', 'requests'], ['Answers', 'answers']]) )%></td>
</tr>
</table>
<%= submit_tag("Apply Filters") %>
<% end %>
</div>

app/views/users/_user.html.erb
<tr>
<td><%= link_to full_name(user), user %></td>
<td><%= user.username %></td>
<td><% if !user.family.nil? %>
    <%= link_to user.family.family_name, user.family %>
    <% end %>
</td>
<% if current_user.admin? %>
<td><% if !user.table.nil? %>
      <%= link_to user.table.number, user.table %>
	<% end %></td>
<% if !user.is_coming %>
  <td></td>
<% else %>
  <td><% user_available_tables(@available_tables,user.table_id).each do |table| %>
      <%= link_to table.number, [:add_user, user, table] %>  
    <% end %>
  </td>
<% end %>
<td><%= "#{user.get_guess_who_right_answers_count}/#{user.get_answered_questions_count}" %></td>
<td><%= user.logins %></td>
<td><%= user.song_requests.size %></td>
<td><%= user.get_total_points %></td>
<% end %> 
<td> 
	<ul>
			<% if current_user.admin? || current_user?(user) %>
     		<li><%= link_to "edit", edit_user_path(user) %></li>
     		
     		<li>
     			<% if user.activated? %>
     			 	<%= link_to "deactivate", deactivate_user_path(user) %>
     			<% else %>
     			 	<%= link_to "activate", activate_user_path(user) %>
     			<% end %>
     		</li>
     		
     		<li>
     			<% if user.invited? %>
     			 	<%= link_to "uninvite", uninvite_user_path(user) %>
     			<% else %>
     			 	<%= link_to "invite", invite_user_path(user) %>
     			<% end %>
     		</li>
     		
     		<li>
     			<% if user.is_coming? %>
     			 	<%= link_to "is not coming", isnotcoming_user_path(user) %>
     			<% else %>
     			 	<%= link_to "is coming", iscoming_user_path(user) %>
     			<% end %>
     		</li>
     		
     		<li>
     			<% if user.is_adult? %>
     			 	<%= link_to "is kid or vendor", set_is_not_adult_user_path(user) %>
     			<% else %>
     			 	<%= link_to "is adult", set_is_adult_user_path(user) %>
     			<% end %>
     		</li>
     		
     			<% if user.table %><li>
     			 	<%= link_to "remove from table", untable_user_path(user) %>
     			</li><% end %>
     	<% if current_user.admin? && !current_user?(user) %>
   			<li><%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %></li>
     	<% end %>
      <% end %>
     </ul>
</td>

</tr>

app/views/users/_user_headers.html.erb
<tr>
    <th>Full Name</th>
    <th>Username</th>
    <th>Family</th>
    <% if current_user.admin? %>
       <th>Table Number</th>
       <th>Add To Table</th>
       <th>Guess Who Right</th>
       <th>Logins</th>
       <th>Requests</th>
       <th>Points</th>
    <% end %>		
    <th>Actions</th>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update <%= @user.first_name %>'s profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
      
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
	
	  <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
	  
	  <% if current_user.admin? %>
		<%= f.label :family %>
		<%= f.collection_select(:family_id, Family.all.order(:family_name), :id, :family_name) %>
      
        <%= f.label :admin %>
        <%= f.check_box :admin, class: 'form-control' %>
        
        <%= f.label :invited %>
        <%= f.check_box :invited, class: 'form-control' %>
        
        <%= f.label :is_coming %>
        <%= f.check_box :is_coming, class: 'form-control' %>
     <% end %> 
     
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <!--div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div-->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All guests') %>
<div class="center jumbotron">
	<h1>All guests</h1>
	<h3>We now have <%= User.count %> guests!!!</h3>
	<h3><%= User.where(is_coming: true).count %> guests are coming:</h3>
	<h3>125 base adults.</h3>
	<h3><%= User.where(is_adult: true).where(is_coming: true).count - 125 %> extra adults.</h3>
	<h3><%= User.where(is_adult: false).where(is_coming: true).count %> children or vendors.</h3>
	<%= link_to "Add guest!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

<%= render 'filters' %>

<div>
</div>


<% unless @users.empty? %>
  <%= will_paginate %>
<% end %>

<table>
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Password</th>
    <th>Password Confirmation</th>
    <th>Family</th>	
    <th>Actions</th>
</tr>
<%= form_for(@user=User.new) do |f| %>
      <%= render 'shared/error_messages' %>
<tr>  
  <td><%= f.text_field :first_name, size: 15 %></td>
  <td><%= f.text_field :last_name, size: 15 %></td>
  <td><%= f.password_field :password, :value => 'password',  class: 'form-control' %></td>
  <td><%= f.password_field :password_confirmation, :value => 'password',  class: 'form-control' %></td>
  <td><%= f.collection_select(:family_id, Family.all.order(:family_name), :id, :family_name) %></td>
  <td><%= f.submit "add guest" %></td>
</tr>
<% end %>
</table>

<table>
  
  <%= render 'user_headers' %>

  <%= render @users %>
</table>

<% unless @users.empty? %>
  <%= will_paginate %>
<% end %>

app/views/users/index_coming.erb
<% provide(:title, 'Final Guest Count') %>
<div class="center jumbotron">
	<h1>Final Guests Count</h1>
	<h3>Guests: <%= adult_count %></h3>
	<h3>Children: <%= child_count %></h3>
	<h3>Vendors: <%= vendor_count %></h3>
</div>

<table>
<tr><td>Table #</td><td>Name</td><td>Table #</td><td>Name</td><td>Table #</td><td>Name</td></tr>
<tr>
<% @users.each do |guest| %>
	<td><%= guest.table.number unless guest.table.nil? %></td><td><%= full_name(guest) %></td>
    <% @count+=1 %>
    <% if @count%3==0 %></tr><tr>
	<% end %>
<% end %>
</tr>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
	
	  <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
	  
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password ('password' by default)" %>
      <%= f.password_field :password, :value => 'password',  class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, :value => 'password',  class: 'form-control' %>
      
      <%= f.label :family %>
      <%= f.collection_select(:family_id, Family.all.order(:family_name), :id, :family_name) %>
      
      <% if current_user.admin? %>
        <%= f.label :admin %>
        <%= f.check_box :admin, class: 'form-control' %>
        
        <%= f.label :invited %>
        <%= f.check_box :invited, class: 'form-control' %>
        
        <%= f.label :is_coming %>
        <%= f.check_box :is_coming, class: 'form-control' %>
        
        <%= f.label :activated %>
        <%= f.check_box :activated, class: 'form-control' %>
     <% end %>

      <%= f.submit "Create account.", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.first_name %>
      </h1>
    </section>
  </aside>
</div>

<% if logged_in_admin? %>
<div>
Welcome message will be here
</div>
<div>
Add questions for the guest to interact
</div>
<div>
Add the list of games (maybe)
</div>
<% else %>
<div>
Welcome <%= @user.first_name %>. Thank you for considering coming to our wedding! We are all excited!<br>
Please stay tuned for more info and fun!!!<br>
Sam & Seb
</div>
<% end %>