config/routes.rb
Rails.application.routes.draw do

  resources :song_requests

  resources :pictures

  resources :tables do
    member do
	   get :empty
	end
  end

  root               		'static_pages#home'
  get 		'home'    	=> 	'static_pages#home'
  get 		'about'   	=>  'static_pages#about'
  get		'wedding' 	=>  'static_pages#wedding'
  get		'venue_cost' 	=>  'static_pages#venue_cost'
  get		'our_story' =>  'static_pages#our_story'
  get		'contact_us' =>  'static_pages#contact_us'
  get		'signup'  	=>	'users#new'
  get    	'login'   	=> 	'sessions#new'
  post   	'login'   	=> 	'sessions#create'
  delete 	'logout'  	=> 	'sessions#destroy'
  get       'flip_theme'    =>      'tables#flip_theme'
  post      'twilio/voice'   =>  'twilio#voice'
  post      'twilio/notify'  =>  'twilio#notify'
  get       'coming_guests' => 'users#index_coming'

  resources :users do
  	member do
  		get :activate
  		get :deactivate
  		get :invite
  		get :uninvite
  		get :iscoming
  		get :isnotcoming
  		get :set_is_not_adult
  		get :set_is_adult
        get ':action/:table_id'
        get :untable
  	end
    resources :tables do
        member do
		   get :add_user
		   get :remove_user
        end
		  
     end
  end
  
  resources :guess_who_questions do
  	member do
  		get :save_user_answer
  	end
  end
  
  resources :families do
    member do
        get :untable
  	end
  
	resources :tables do
        member do
		   get :add_family
           get :remove_family
        end
	end
  end
  
  resources :messages do
  	member do
  		get :mark_as_read
  		get :mark_as_unread
  	end
  end
  
  resources :account_activations, only: [:edit]

  

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def empty
    new_table = Table.find(params[:id])
	new_table.users.each do |user|
	   user.untable
	end
	redirect_to :back
  end
  
  def add_user
    new_table = Table.find(params[:id])
	new_user = User.find(params[:user_id])
	new_table.add_user(new_user)
    redirect_to :back
  end
  
  def remove_user
    new_user = User.find(params[:user_id])
    new_table = Table.find(params[:id])
    new_user.update_attribute(:table_id,null)
    redirect_to :back
  end
  
  def add_family
    new_family = Family.find(params[:family_id])
    new_table = Table.find(params[:id])
    new_family.not_seated.each do |new_user|
      answer = new_table.add_user(new_user)
	  if answer.nil?
	    flash[:danger] = "Flight to #{new_table.name} is now full. Find another destination for the other #{new_family.not_seated.size} guests."
	  end
	end
    redirect_to :back
  end
  
  def remove_family
    new_family = Family.find(params[:family_id])
    new_table = Table.find(params[:id])
	new_family.seated.each do |new_user|
		#new_user.update_attribute(:table_id,null)
	end
    redirect_to :back
  end

  def flip_theme
    new_user = current_user
    new_user.flip_theme
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:number,:capacity)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tables</h1>
<h2><%= link_to get_theme(current_user.theme), flip_theme_path %></h2>

<table>
  <thead>
    <tr>
      <th>Table #</th>
      <th>Table Name</th>
      <th>Capacity</th>
      <th>Available</th>
      <th colspan="3"></th>
      <th>Guests</th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= link_to table.number, table %></td>
        <td><%= table_name(table) %></td>
        <td><%= table.capacity %></td>
        <td><%= table.available_seats %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'Empty', empty_table_path(table) %></td>
        <td><% table.users.order(:last_name).each do |guest| %>
        <%= "#{guest.first_name} #{guest.last_name}" %>,
        <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center jumbotron">  
	<%= image_tag(table_url(@table), :height => "75%", :width => "75%", alt: table_url(@table)) %>
</div>
<p>
  <strong>Table Number:</strong>
  <%= @table.number %><br>
</p>
<p>
  <strong>Table Name:</strong>
  <%= table_name(@table) %><br>
</p>
<p>
  <strong>Capacity:</strong>
  <%= @table.capacity %><br>
</p>
<p>
  <strong>Guests:</strong>
  <%= @table.users.size %><br>
</p>
<p> <strong>Guests:</strong>
  <ul>
    <% @table.users.each do |guest| %>
      <li><%= link_to full_name(guest), guest %>: 
          <%= link_to "remove", untable_user_path(guest) %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>