config/routes.rb
Rails.application.routes.draw do

  resources :song_requests

  resources :pictures

  resources :tables do
    member do
	   get :empty
	end
  end

  root               		'static_pages#home'
  get 		'home'    	=> 	'static_pages#home'
  get 		'about'   	=>  'static_pages#about'
  get		'wedding' 	=>  'static_pages#wedding'
  get		'venue_cost' 	=>  'static_pages#venue_cost'
  get		'our_story' =>  'static_pages#our_story'
  get		'contact_us' =>  'static_pages#contact_us'
  get		'signup'  	=>	'users#new'
  get    	'login'   	=> 	'sessions#new'
  post   	'login'   	=> 	'sessions#create'
  delete 	'logout'  	=> 	'sessions#destroy'
  get       'flip_theme'    =>      'tables#flip_theme'
  post      'twilio/voice'   =>  'twilio#voice'
  post      'twilio/notify'  =>  'twilio#notify'
  get       'coming_guests' => 'users#index_coming'

  resources :users do
  	member do
  		get :activate
  		get :deactivate
  		get :invite
  		get :uninvite
  		get :iscoming
  		get :isnotcoming
  		get :set_is_not_adult
  		get :set_is_adult
        get ':action/:table_id'
        get :untable
  	end
    resources :tables do
        member do
		   get :add_user
		   get :remove_user
        end
		  
     end
  end
  
  resources :guess_who_questions do
  	member do
  		get :save_user_answer
  	end
  end
  
  resources :families do
    member do
        get :untable
  	end
  
	resources :tables do
        member do
		   get :add_family
           get :remove_family
        end
	end
  end
  
  resources :messages do
  	member do
  		get :mark_as_read
  		get :mark_as_unread
  	end
  end
  
  resources :account_activations, only: [:edit]

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made by Sebastien Thomas
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact Us", new_message_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Sam & Seb", '#', id: "logo" %>
        <nav>
          	<ul class="nav navbar-nav navbar-right">
            	<li><%= link_to "Home", root_path %></li>
            	<% if logged_in? %>
            		<% if current_user.admin? %>
					<li><%= link_to "Messages (#{Message.where(new_message: true).count})", messages_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Others <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Guests", users_path %></li>
							<li><%= link_to "Final Guest List", coming_guests_path %></li>
							<li><%= link_to "Venue Cost", venue_cost_path %></li>
							<li><%= link_to "Tables", tables_path %></li>
							<li><%= link_to "Pictures", pictures_path %></li>
							<li><%= link_to "Families", families_path %></li>
							<li><%= link_to "Song Requests", song_requests_path %></li>
						</ul>
					</li>
  					<% end %>
  					<% if current_user.admin? || true %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Games <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Guess Who!", guess_who_questions_path %></li>
							</ul>
						</li>
  					<% end %>
          			<li class="dropdown">
            		  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              			Account <b class="caret"></b>
            		  </a>
            		  <ul class="dropdown-menu">
              			<li><%= link_to "Profile", current_user %></li>
              			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
              			<li class="divider"></li>
              			<li>
                		  <%= link_to "Log out", logout_path, method: "delete" %>
              			</li>
            		  </ul>
          		   	</li>
        		<% else %>
          			<li><%= link_to "Log in", login_path %></li>
        		<% end %>
          	</ul>
    	</nav>
	</div>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
    <% if logged_in_admin? && false %>
      <%= debug(params) if Rails.env.development? %>
    <% end %>
      
      <%= render 'layouts/message' %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>